# Generated by Django 5.0.6 on 2024-06-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Резюме')),
                ('cover_letter', models.TextField(null=True, verbose_name='Сопроводительное письмо')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('position', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile dev', 'Mobile dev'), ('devops', 'Devops'), ('qa', 'QA'), ('project manager', 'Project Manager')], max_length=50, null=True, verbose_name='Позиция кандидата')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата собеседовании')),
                ('feedback', models.TextField(null=True, verbose_name='Фидбэк')),
                ('rating', models.IntegerField(null=True, verbose_name='Рейтинг')),
                ('portfolio_link', models.URLField(null=True, verbose_name='Ссылка на портфолио')),
                ('github_profile', models.URLField(null=True, verbose_name='Ссылка на гитхаб')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_service.candidateprofile', verbose_name='Кандидат')),
            ],
        ),
    ]
