# Generated by Django 5.0.6 on 2024-06-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_service', '0002_candidateprofile_last_name_candidateprofile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_author', to='application_service.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_service.candidateprofile')),
            ],
        ),
    ]
