# Generated by Django 5.0.6 on 2024-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_service', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/', verbose_name='Резюме'),
        ),
    ]
